version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 100
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
  - package-ecosystem: 'github-actions'
    directory: '/'
    open-pull-requests-limit: 100
    schedule:
      interval: 'daily'
